name: farallon-fall-2020
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pangeo-notebook=2020.06.03
  - argopy
  - beautifulsoup4
  - bokeh
  - bottleneck
  - cartopy
  - cdsapi
  - cf-units
  - cf_xarray
  - cftime
  - cfgrib
  - colorcet
  - compilers
  - ctd
  - datashader
  - dask
  - distributed
  - erddapy
  - fsspec
  - geolinks
  - geopandas
  - geoviews
  - gsw
  - holoviews
  - hvplot
  - h5netcdf
  - h5py
  - ioos-tools
  - ioos_qc
  - iris
  - ipyleaflet
  - jupyter
  - jupyter-rsession-proxy
  - jupyter_contrib_nbextensions
  - jupyterlab
  - lxml
  - matplotlib
  - nc-time-axis
  - netcdf4
  - numpy
  - numbagg
  - palettable
  - pandas<1.1
  - panel
  - param
  - pint
  - podaacpy
  - PseudoNetCDF
  - pyoos
  - pydap
  - pynio
  - rasterio
  - requests
  - retrying
  - satpy
  - scikit-learn
  - scipy
  - seaborn
  - seawater
  - shapely
  - siphon
  - s3fs
  - xarray
  - xlrd
  - zarr
